<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74062" started-at="2016-05-13T10:34:06Z" finished-at="2016-05-13T10:35:20Z">
    <groups>
    </groups>
    <test name="LATimesAndroidTest" duration-ms="74062" started-at="2016-05-13T10:34:06Z" finished-at="2016-05-13T10:35:20Z">
      <class name="com.LATimes.tests.LATimesCallingFunctions">
        <test-method status="PASS" signature="testSetUp(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.LATimes.tests.LATimesCallingFunctions@1e88b3c]" name="testSetUp" is-config="true" duration-ms="19555" started-at="2016-05-13T16:04:06Z" finished-at="2016-05-13T16:04:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy S5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8001]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.tribune.universalnews.MainActivity]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[com.apptivateme.next.la]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method status="FAIL" signature="swipeThroughSectionFronts()[pri:0, instance:com.LATimes.tests.LATimesCallingFunctions@1e88b3c]" name="swipeThroughSectionFronts" duration-ms="52316" started-at="2016-05-13T16:04:25Z" finished-at="2016-05-13T16:05:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User was able to swipe through sections fronts to and fro SUCCESSFULLY expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User was able to swipe through sections fronts to and fro SUCCESSFULLY expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at com.LATimes.tests.LATimesCallingFunctions.swipeThroughSectionFronts(LATimesCallingFunctions.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- swipeThroughSectionFronts -->
        <test-method status="PASS" signature="Exit()[pri:0, instance:com.LATimes.tests.LATimesCallingFunctions@1e88b3c]" name="Exit" is-config="true" duration-ms="2107" started-at="2016-05-13T16:05:18Z" finished-at="2016-05-13T16:05:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Exit -->
      </class> <!-- com.LATimes.tests.LATimesCallingFunctions -->
    </test> <!-- LATimesAndroidTest -->
  </suite> <!-- Suite -->
</testng-results>
